import 'dart:math';

void main() {
  final random = Random();

  const adjectives = [
    "Barmy",
    "Bossy",
    "Bulgy",
    "Chary",
    "Cozy",
    "Daffy",
    "Dorky",
    "Goofy",
    "Goury",
    "Gawky",
    "Huffy",
    "Izzat",
    "Jazzy",
    "Jiffy",
    "Kooky",
    "Loony",
    "Mushy",
    "Miffed",
    "Namby",
    "Nutty",
    "Oily",
    "Orery",
    "Pudge",
    "Queer",
    "Reedy",
    "Runty",
    "Sassy",
    "Scram",
    "Seed",
    "Shady",
    "Slimy",
    "Soppy",
    "Spoofy",
    "Swanky",
    "Tacky",
    "Tipsy",
    "Twee",
    "Unco",
    "Vague",
    "Wacky",
    "Waney",
    "Weedy",
    "Wheezy",
    "Wimpy",
    "Wonky",
    "Woozy",
    "Yeasty",
    "Zesty",
    "Zippy",
    "Zooky",
  ];

  const nouns = [
    "Bongo",
    "Booby",
    "Boozer",
    "Bribe",
    "Chump",
    "Clack",
    "Clown",
    "Codex",
    "Coot",
    "Corgi",
    "Crump",
    "Dingo",
    "Dinky",
    "Doodad",
    "Doofus",
    "Dummy",
    "Fudge",
    "Gazer",
    "Geek",
    "Gismo",
    "Glitch",
    "Golem",
    "Goon",
    "Gumbo",
    "Guppy",
    "Guzzy",
    "Hoax",
    "Hubbub",
    "Hussy",
    "Idiot",
    "Jumbo",
    "Kappa",
    "Kazoo",
    "Kedge",
    "Klutz",
    "Larva",
    "Llama",
    "Loofah",
    "Mummy",
    "Ninja",
    "Omlah",
    "Panda",
    "Pixie",
    "Plonk",
    "Pooch",
    "Quack",
    "Squib",
    "Toad",
    "Voodoo",
    "Zombie",
  ];

  const numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
  const symbols = ["!", "@", "#", "%", "&"];

  final numbersAndSymbols = [
    for (var i = 0; i < 2; i++) ...[
      numbers[random.nextInt(numbers.length)],
      symbols[random.nextInt(symbols.length)],
    ],
  ]..shuffle(random);

  final targetList = [
    adjectives[random.nextInt(adjectives.length)],
    nouns[random.nextInt(nouns.length)],
    ...numbersAndSymbols,
  ];

  print(targetList.join());
}
